services:
  db__test:
    image: postgres
    container_name: db__test
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db__test
    env_file:
      - .env.test